CREATE ROLE effect
  LOGIN PASSWORD 'effect'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

GRANT CONNECT ON DATABASE effect_erp TO effect;
GRANT USAGE ON SCHEMA public TO effect;

ALTER DEFAULT PRIVILEGES FOR ROLE effect_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO effect;
